train_params:
    model_path: "./models/random_forest.pkl"
    metrics_path: "./reports/report.json"
    n_estimators: 500
data_params:
    raw_data_path: ""
    train_data_path: "./data/processed/train.csv"
    test_data_path: "./data/processed/test.csv"
    n_samples: 100
    n_features: 10
    test_size: 0.3

random_state: 42