name: ci pipeline

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Run linting
        run: pylint src tests

      - name: Run tests
        run: pytest tests